import {
  AlleyIcon,
  BankIcon,
  BlackmarketIcon,
  BuildingsIcon,
  CasinoIcon,
  ClubIcon,
  DealerIcon,
  DistrictsIcon,
  GangIcon,
  HospitalIcon,
  LadyIcon,
  MarketIcon,
  PrisonIcon,
  RobberyIcon,
  SabotageIcon,
  UniversityIcon,
} from "@/components/ui/icons";

const actionIconsStyles = { width: 48, height: 48 };

const userActions = [
  {
    ...actionIconsStyles,
    component: RobberyIcon,
    viewBox: "512 512",
    actionName: "Robbery",
    href: "/robbery",
  },
  {
    ...actionIconsStyles,
    component: GangIcon,
    viewBox: "512 512",
    actionName: "Gang",
    href: "/gang",
  },
  {
    ...actionIconsStyles,
    component: ClubIcon,
    viewBox: "48 48",
    actionName: "Night club",
    href: "/nightclub",
  },
  {
    ...actionIconsStyles,
    component: SabotageIcon,
    viewBox: "512 512",
    actionName: "Sabotage",
    href: "/sabotage",
  },
  {
    ...actionIconsStyles,
    component: LadyIcon,
    viewBox: "48 48",
    actionName: "Whores",
    href: "/whores",
  },
  {
    ...actionIconsStyles,
    component: BlackmarketIcon,
    viewBox: "512 512",
    actionName: "Black market",
    href: "/blackmarket",
  },
  {
    ...actionIconsStyles,
    component: DealerIcon,
    viewBox: "44 44",
    actionName: "Dealer",
    href: "/dealer",
  },
  {
    ...actionIconsStyles,
    component: MarketIcon,
    viewBox: "1024 1024",
    actionName: "Market",
    href: "/market",
  },
  {
    ...actionIconsStyles,
    component: BuildingsIcon,
    viewBox: "54 54",
    actionName: "Buildings",
    href: "/buildings",
  },
  {
    ...actionIconsStyles,
    component: DistrictsIcon,
    viewBox: "512 512",
    actionName: "Districts",
    href: "/districts",
  },
  {
    ...actionIconsStyles,
    component: AlleyIcon,
    viewBox: "420 420",
    actionName: "Alley",
    href: "/alley",
  },
  {
    ...actionIconsStyles,
    component: UniversityIcon,
    viewBox: "481 481",
    actionName: "University",
    href: "/university",
  },
  {
    ...actionIconsStyles,
    component: HospitalIcon,
    viewBox: "512 512",
    actionName: "Hospital",
    href: "/hospital",
  },
  {
    ...actionIconsStyles,
    component: BankIcon,
    viewBox: "64 64",
    actionName: "Bank",
    href: "/bank",
  },
  {
    ...actionIconsStyles,
    component: CasinoIcon,
    viewBox: "33 33",
    actionName: "Casino",
    href: "/casino",
  },
  {
    ...actionIconsStyles,
    component: PrisonIcon,
    viewBox: "14 14",
    actionName: "Prison",
    href: "/prison",
  },
];
export default userActions;
