const avatarItems = [
  { src: "av1" },
  { src: "av2" },
  { src: "av3" },
  { src: "av4" },
  { src: "av5" },
  { src: "av6" },
  { src: "av7" },
  { src: "av8" },
  { src: "av9" },
  { src: "av10" },
  { src: "av11" },
  { src: "av12" },
  { src: "av13" },
  { src: "av14" },
  { src: "av15" },
  { src: "av16" },
  { src: "av17" },
  { src: "av18" },
  { src: "av19" },
  { src: "av20" },
];
export default avatarItems;
