name: syndicatecrimeClient
on:
  push:
    branches: [main, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
      CONNECTION_URL: ${{secrets.CONNECTION_URL}}
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
      NEXT_PUBLIC_WEBSOCKET_URL: ${{secrets.NEXT_PUBLIC_WEBSOCKET_URL}}
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build
      - run: mkdir ~/.ssh
      - run: echo "$SSH_KEY" >> ~/.ssh/github-action
      - run: chmod 400 ~/.ssh/github-action
      - run: echo -e "Host vps\n\tUser ubuntu\n\tHostname 152.70.166.180\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
      - name: Rsync to develop or main folder
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            rsync -re ssh ./.next/ vps:/home/ubuntu/syndicateCrime/.next
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            rsync -re ssh ./.next/ vps:/home/ubuntu/syndicateCrimeDevelop/.next
          fi

      - name: Restart App
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            ssh vps "pm2 restart syndicateClient"
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            ssh vps "pm2 restart syndicateClientDevelop"
          fi
